### Get all products
GET http://localhost:3000/product/all
### Get one products
GET http://localhost:3000/product/2

### Create new product
POST http://localhost:3000/product/new
content-type: application/json

{
  "name": "Wood table",
  "sku": "TB100",
  "category": 2,
  "description": "A table for kitchen",
  "large_description": "A table for kitchen",
  "price": 499.99,
  "is_new": true,
  "image_link": "placeholder.jpg"
}

### Update a product
PATCH  http://localhost:3000/product/update/2

{
  "name": "Other name",
}


### Delete a product
DELETE   http://localhost:3000/product/delete/9
